version: 2.1

orbs:
  ruby: circleci/ruby@1.4.0

jobs:
  backend_build:
    docker:
      - image: cimg/ruby:2.7.2
    working_directory: ~/JPforMMA/app/backend
    steps:
      - checkout:
          path: ~/JPforMMA
      - ruby/install-deps
  backend_deploy:
    machine:
        image: circleci/classic:edge
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "19:36:45:71:aa:24:96:47:c9:c1:97:da:73:94:28:f8"
      - run: 
          name: ssh login
          command: ssh ${USER_NAME}@${HOST_NAME} "cd JPforMMA/app/backend && git pull origin master && sudo docker-compose -f docker-compose.production.yml build && sudo docker-compose -f docker-compose.production.yml rails rails --rm db:migrate RAILS_ENV=production"

workflows:
  build_and_deploy:
    jobs:
      - backend_build
      - backend_deploy:
          requires:
            - backend_build
          filters:
            branches:
              only: master
