version: 2.1

orbs:
  ruby: circleci/ruby@1.4.0

jobs:
  backend_build:
    docker:
      - image: cimg/ruby:2.7.2
    working_directory: ~/JPforMMA/app/backend
    steps:
      - checkout:
          path: ~/JPforMMA
      - ruby/install-deps
  backend_deploy:
    docker:
      - image: circleci/ruby:2.7.2
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "67:56:00:5c:99:75:07:42:79:6c:e3:32:9d:1b:7b:cf"
      - run: 
          name: ssh login
          command: ssh -o StrictHostKeyChecking=no ${USER_NAME}@${HOST_NAME}
      - run:
          name: cd & git pull
          command: cd JPforMMA/app/backend && git pull origin master
      - run:
          name: build
          command: sudo docker-compose -f docker-compose.production.yml build 
      - run:
          name: migrate
          command: sudo docker-compose -f docker-compose.production.yml rails rails --rm db:migrate RAILS_ENV=production

workflows:
  build_and_deploy:
    jobs:
      - backend_build
      - backend_deploy:
          requires:
            - backend_build
          filters:
            branches:
              only: master
