version: 2.1

orbs:
  ruby: circleci/ruby@1.4.0

jobs:
  backend_build:
    docker:
      - image: cimg/ruby:2.7.2
    working_directory: ~/JPforMMA/app/backend
    steps:
      - checkout:
          path: ~/JPforMMA
      - ruby/install-deps
  backend_deploy:
    machine:
        image: circleci/classic:edge
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "19:36:45:71:aa:24:96:47:c9:c1:97:da:73:94:28:f8"
      - run: 
          name: deploy
          command: ssh ${USER_NAME}@${HOST_NAME} "bash ~/JPforMMA/.circleci/deploy-backend.sh"
  frontend_build:
    docker:
      - image: circleci/node:8.9
    working_directory: ~/JPforMMA/app/frontend
    steps:
      - checkout:
          path: ~/JPforMMA
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn build
  frontend_deploy:
    machine:
        image: circleci/classic:edge
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "19:36:45:71:aa:24:96:47:c9:c1:97:da:73:94:28:f8"
      - run: 
          name: deploy
          command: ssh ${USER_NAME_FRONTEND}@${HOST_NAME} "bash ~/JPforMMA/.circleci/deploy-backend.sh"

workflows:
  build_and_deploy:
    jobs:
      - backend_build
      - backend_deploy:
          requires:
            - backend_build
          filters:
            branches:
              only: master
      - frontend_build
      - frontend_deploy:
          requires:
            - frontend_build
          filters:
            branches:
              only: master
