version: '3'
services:
  db:
    image: mysql:8.0
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./db/mysql_data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - "3306:3306"
  rails:
    build: .
    container_name: rails
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app/backend
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development
    env_file:
      - .env
    depends_on:
      - db