version: "3.9"
services:
  rails:
    build: .
    container_name: rails
    command: bundle exec puma -C config/puma.rb -e production
    volumes:
      - .:/app
      - public-data:/app/public
      - tmp-data:/app/tmp
      - log-data:/app/log
      - /app/node_modules
    env_file:
      - .env
    # depends_on:
    #   - db
    user: root

  # db:
  #   image: mysql:8.0
  #   container_name: db
  #   environment:
  #     TZ: Asia/Tokyo
  #     # MYSQL_ROOT_PASSWORD: password
  #     MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
  #   ports:
  #     - "3306:3306"
  #   volumes:
  #     - ./db/mysql_data:/var/lib/mysql
  
  web:
    build:
      context: nginx
    volumes:
      - public-data:/app/public
      - tmp-data:/app/tmp
    ports:
      - 80:80
    depends_on:
      - rails

volumes:
  # db:
  #   driver: local
  public-data:
  tmp-data:
  log-data: